### ISSUE TITLE
Retrieve snippet information from the database and create skeleton of snippet

### ISSUE THREAD

**Issue by nsteward96** [MCLACS/CSCI452-FA17-Public#12]
JS Team is going to have to retrieve the summary information of each snippet and create a div 'skeleton' to hold the information from the snippet.

Sketch of a potential simple Snippet skeleton (styling not included, just layout):

Ver 1
![vs1-snippetskeletonsketch](https://user-images.githubusercontent.com/16218207/30254129-d3e17d14-9661-11e7-885f-3de9a7e1a32c.png)
Ver 2
![vs1-snippetskeletonsketch2](https://user-images.githubusercontent.com/16218207/30255160-4e14d416-966f-11e7-89e1-7b5f16069cf4.png)

**Comment by pchase95** [comment]
Since we're showing a list of snippet summaries I believe an individual summary should be much smaller.  In my opinion each summary should be 3 lines.  A title bar to display the name, author and language.  The next lines should contain a short description.  The last line should display a part of the snippet. onmouseover this should blow up to a full snippet summary.

**Comment by nsteward96** [comment]
That's a good idea. We may want to use onclick instead of onmouseover though, users might not want stuff to be blowing up on their screen all the time.

**Comment by nsteward96** [comment]
Merged.
