### ISSUE TITLE
Implement response to root path

### ISSUE THREAD

**Issue by Liima** [MCLACS/CSCI452-FA17-Public#2]
__To complete this issue, we need to write the php code that will serve the home page of our application and will pass the relevant tests in #1__

**Comment by JPhilibert** [comment]
description: create php function to supply snippetgood.com when requested

**Comment by MCLACS** [comment]
I am not sure that this is required for the first sprint.  A home page is not necessary for VS1.  You can leave this task in, but do not assign it to a user story yet until it is needed.

**Comment by Liima** [comment]
I'm confused by that, doesn't the client need the html page containing all the scripts and stylesheets to render the page elements?  Is that not a part of this deliverable?

**Comment by MCLACS** [comment]
The PHP pages in this application should never serve HTML — they should only return JSON.  This is a supposed to be a single page application, so there is only one HTML page.   The client will access the single HTML page directly (no PHP needed) — I recommend calling it index.html so that it comes down automatically on the root path.  Once the single page is loaded it will get want it needs by "pinging" the PHP API you guys write.  For the first sprint, the only API needed bis "give me th list of snippets".  I hope this makes sense.
